import * as React from 'react';
export type IconName =
  | "AIPromptSize16StyleOutline" | "AIPromptSize24StyleOutline" | "AIPromptSize32StyleOutline"
  | "AISearchSize16StyleOutline" | "AISearchSize24StyleOutline"
  | "AddUserSize16StyleFill" | "AddUserSize16StyleOutline" | "AddUserSize24StyleFill" | "AddUserSize24StyleOutline"
  | "AdjustmentSize16StyleFill" | "AdjustmentSize16StyleOutline" | "AdjustmentSize24StyleFill" | "AdjustmentSize24StyleOutline" | "AdjustmentSize32StyleFill" | "AdjustmentSize32StyleOutline"
  | "AngleSize16StyleFill" | "AngleSize16StyleOutline" | "AngleSize24StyleFill" | "AngleSize24StyleOutline" | "AngleSize32StyleFill" | "AngleSize32StyleOutline"
  | "AnnouncementSize16StyleFill" | "AnnouncementSize16StyleOutline" | "AnnouncementSize24StyleFill" | "AnnouncementSize24StyleOutline"
  | "ArchiveSize16StyleFill" | "ArchiveSize16StyleOutline" | "ArchiveSize24StyleFill" | "ArchiveSize24StyleOutline" | "ArchiveSize28StyleFill" | "ArchiveSize28StyleOutline" | "ArchiveSize44StyleFill" | "ArchiveSize44StyleOutline"
  | "ArrowDownSize16StyleOutline" | "ArrowDownSize24StyleOutline" | "ArrowDownSize32StyleOutline" | "ArrowDownSize44StyleOutline"
  | "ArrowLeftSize16StyleOutline" | "ArrowLeftSize24StyleOutline" | "ArrowLeftSize32StyleOutline" | "ArrowLeftSize44StyleOutline"
  | "ArrowRightSize16StyleOutline" | "ArrowRightSize24StyleOutline" | "ArrowRightSize32StyleOutline" | "ArrowRightSize44StyleOutline"
  | "ArrowUpSize16StyleOutline" | "ArrowUpSize24StyleOutline" | "ArrowUpSize32StyleOutline" | "ArrowUpSize44StyleOutline"
  | "BankCardSize16StyleFill" | "BankCardSize16StyleOutline" | "BankCardSize24StyleFill" | "BankCardSize24StyleOutline"
  | "BookmarkAddSize16StyleFill" | "BookmarkAddSize16StyleOutline" | "BookmarkAddSize24StyleFill" | "BookmarkAddSize24StyleOutline" | "BookmarkAddSize44StyleFill" | "BookmarkAddSize44StyleOutline"
  | "BookmarkRemoveSize16StyleFill" | "BookmarkRemoveSize16StyleOutline" | "BookmarkRemoveSize24StyleFill" | "BookmarkRemoveSize24StyleOutline"
  | "BookmarkSize16StyleFill" | "BookmarkSize16StyleOutline" | "BookmarkSize24StyleFill" | "BookmarkSize24StyleOutline" | "BookmarkSize28StyleFill" | "BookmarkSize28StyleOutline" | "BookmarkSize32StyleFill" | "BookmarkSize32StyleOutline"
  | "CalendarSize16StyleFill" | "CalendarSize16StyleOutline" | "CalendarSize24StyleFill" | "CalendarSize24StyleOutline" | "CalendarSize28StyleFill" | "CalendarSize28StyleOutline" | "CalendarSize32StyleFill" | "CalendarSize32StyleOutline" | "CalendarSize44StyleFill" | "CalendarSize44StyleOutline"
  | "CallSize16StyleFill" | "CallSize16StyleOutline" | "CallSize24StyleFill" | "CallSize24StyleOutline" | "CallSize28StyleFill" | "CallSize28StyleOutline" | "CallSize32StyleFill" | "CallSize32StyleOutline"
  | "CameraSize16StyleFill" | "CameraSize16StyleOutline" | "CameraSize24StyleFill" | "CameraSize24StyleOutline" | "CameraSize28StyleFill" | "CameraSize28StyleOutline" | "CameraSize32StyleFill" | "CameraSize32StyleOutline" | "CameraSize44StyleFill" | "CameraSize44StyleOutline"
  | "CatalogSize16StyleOutline" | "CatalogSize24StyleOutline" | "CatalogSize32StyleOutline" | "CatalogSize44StyleOutline"
  | "ChatSize16StyleFill" | "ChatSize16StyleOutline" | "ChatSize24StyleFill" | "ChatSize24StyleOutline" | "ChatSize32StyleFill" | "ChatSize32StyleOutline" | "ChatSize44StyleFill" | "ChatSize44StyleOutline"
  | "CheckCircleSize16StyleFill" | "CheckCircleSize16StyleOutline" | "CheckCircleSize24StyleFill" | "CheckCircleSize24StyleOutline" | "CheckCircleSize28StyleFill" | "CheckCircleSize28StyleOutline" | "CheckCircleSize32StyleFill" | "CheckCircleSize32StyleOutline" | "CheckCircleSize44StyleFill" | "CheckCircleSize44StyleOutline"
  | "CheckSize16StyleOutline" | "CheckSize24StyleOutline" | "CheckSize32StyleOutline" | "CheckSize44StyleOutline"
  | "ChecklistSize16StyleOutline" | "ChecklistSize24StyleOutline" | "ChecklistSize32StyleOutline"
  | "CompanySize16StyleFill" | "CompanySize16StyleOutline" | "CompanySize24StyleFill" | "CompanySize24StyleOutline"
  | "ContactsSize16StyleFill" | "ContactsSize16StyleOutline" | "ContactsSize24StyleFill" | "ContactsSize24StyleOutline" | "ContactsSize28StyleFill" | "ContactsSize28StyleOutline" | "ContactsSize32StyleFill" | "ContactsSize32StyleOutline"
  | "CopySize16StyleFill" | "CopySize16StyleOutline" | "CopySize24StyleFill" | "CopySize24StyleOutline" | "CopySize32StyleFill" | "CopySize32StyleOutline"
  | "CrossCircleSize16StyleFill" | "CrossCircleSize16StyleOutline" | "CrossCircleSize24StyleFill" | "CrossCircleSize24StyleOutline" | "CrossCircleSize32StyleFill" | "CrossCircleSize32StyleOutline" | "CrossCircleSize44StyleFill" | "CrossCircleSize44StyleOutline"
  | "CrossSize16StyleOutline" | "CrossSize24StyleOutline" | "CrossSize32StyleOutline" | "CrossSize44StyleOutline"
  | "DeleteSize16StyleFill" | "DeleteSize16StyleOutline" | "DeleteSize24StyleFill" | "DeleteSize24StyleOutline" | "DeleteSize28StyleFill" | "DeleteSize28StyleOutline" | "DeleteSize32StyleFill" | "DeleteSize32StyleOutline" | "DeleteSize44StyleFill" | "DeleteSize44StyleOutline"
  | "DocumentSize16StyleFill" | "DocumentSize16StyleOutline" | "DocumentSize24StyleFill" | "DocumentSize24StyleOutline" | "DocumentSize32StyleFill" | "DocumentSize32StyleOutline" | "DocumentSize44StyleFill" | "DocumentSize44StyleOutline"
  | "DownloadSize16StyleOutline" | "DownloadSize24StyleOutline" | "DownloadSize32StyleOutline"
  | "DownloadCircleSize16StyleFill" | "DownloadCircleSize16StyleOutline" | "DownloadCircleSize24StyleFill" | "DownloadCircleSize24StyleOutline"
  | "DuplicateSize16StyleFill" | "DuplicateSize16StyleOutline" | "DuplicateSize24StyleFill" | "DuplicateSize24StyleOutline" | "DuplicateSize32StyleFill" | "DuplicateSize32StyleOutline"
  | "EditSize16StyleFill" | "EditSize16StyleOutline" | "EditSize24StyleFill" | "EditSize24StyleOutline" | "EditSize32StyleFill" | "EditSize32StyleOutline" | "EditSize44StyleFill" | "EditSize44StyleOutline"
  | "EntranceSize16StyleFill" | "EntranceSize16StyleOutline" | "EntranceSize24StyleFill" | "EntranceSize24StyleOutline" | "EntranceSize32StyleFill" | "EntranceSize32StyleOutline" | "EntranceSize44StyleFill" | "EntranceSize44StyleOutline"
  | "ExitSize16StyleFill" | "ExitSize16StyleOutline" | "ExitSize24StyleFill" | "ExitSize24StyleOutline" | "ExitSize28StyleFill" | "ExitSize28StyleOutline" | "ExitSize32StyleFill" | "ExitSize32StyleOutline" | "ExitSize44StyleFill" | "ExitSize44StyleOutline"
  | "FeedbackSize16StyleFill" | "FeedbackSize16StyleOutline" | "FeedbackSize24StyleFill" | "FeedbackSize24StyleOutline"
  | "FilterSize16StyleFill" | "FilterSize16StyleOutline" | "FilterSize24StyleFill" | "FilterSize24StyleOutline" | "FilterSize32StyleFill" | "FilterSize32StyleOutline" | "FilterSize44StyleFill" | "FilterSize44StyleOutline"
  | "FilterOffSize16StyleFill" | "FilterOffSize16StyleOutline" | "FilterOffSize24StyleFill" | "FilterOffSize24StyleOutline"
  | "FolderSize16StyleFill" | "FolderSize16StyleOutline" | "FolderSize24StyleFill" | "FolderSize24StyleOutline" | "FolderSize32StyleFill" | "FolderSize32StyleOutline" | "FolderSize44StyleFill" | "FolderSize44StyleOutline"
  | "FoldersSize16StyleFill" | "FoldersSize16StyleOutline" | "FoldersSize24StyleFill" | "FoldersSize24StyleOutline" | "FoldersSize32StyleFill" | "FoldersSize32StyleOutline"
  | "GavelSize16StyleFill" | "GavelSize16StyleOutline" | "GavelSize24StyleFill" | "GavelSize24StyleOutline"
  | "GeoSize16StyleFill" | "GeoSize16StyleOutline" | "GeoSize24StyleFill" | "GeoSize24StyleOutline"
  | "HeartSize16StyleFill" | "HeartSize16StyleOutline" | "HeartSize24StyleFill" | "HeartSize24StyleOutline" | "HeartSize28StyleFill" | "HeartSize28StyleOutline" | "HeartSize32StyleFill" | "HeartSize32StyleOutline" | "HeartSize44StyleFill" | "HeartSize44StyleOutline"
  | "HelpSize16StyleFill" | "HelpSize16StyleOutline" | "HelpSize24StyleFill" | "HelpSize24StyleOutline"
  | "HideSize16StyleFill" | "HideSize16StyleOutline" | "HideSize24StyleFill" | "HideSize24StyleOutline" | "HideSize32StyleFill" | "HideSize32StyleOutline" | "HideSize44StyleFill" | "HideSize44StyleOutline"
  | "HomeSize16StyleFill" | "HomeSize16StyleOutline" | "HomeSize24StyleFill" | "HomeSize24StyleOutline" | "HomeSize28StyleFill" | "HomeSize28StyleOutline" | "HomeSize32StyleFill" | "HomeSize32StyleOutline" | "HomeSize44StyleFill" | "HomeSize44StyleOutline"
  | "InfoCircleSize16StyleFill" | "InfoCircleSize16StyleOutline" | "InfoCircleSize24StyleFill" | "InfoCircleSize24StyleOutline" | "InfoCircleSize32StyleFill" | "InfoCircleSize32StyleOutline" | "InfoCircleSize44StyleFill" | "InfoCircleSize44StyleOutline"
  | "InformationSize16StyleFill" | "InformationSize16StyleOutline" | "InformationSize24StyleFill" | "InformationSize24StyleOutline" | "InformationSize32StyleFill" | "InformationSize32StyleOutline"
  | "KeysSize16StyleOutline" | "KeysSize24StyleOutline" | "KeysSize44StyleOutline"
  | "LanguageSize16StyleFill" | "LanguageSize16StyleOutline" | "LanguageSize24StyleFill" | "LanguageSize24StyleOutline" | "LanguageSize44StyleFill" | "LanguageSize44StyleOutline"
  | "LikeSize16StyleFill" | "LikeSize16StyleOutline" | "LikeSize24StyleFill" | "LikeSize24StyleOutline" | "LikeSize44StyleFill" | "LikeSize44StyleOutline"
  | "LinkSize16StyleOutline" | "LinkSize24StyleOutline" | "LinkSize32StyleOutline"
  | "LockSize16StyleFill" | "LockSize16StyleOutline" | "LockSize24StyleFill" | "LockSize24StyleOutline" | "LockSize44StyleFill" | "LockSize44StyleOutline"
  | "MailSize16StyleFill" | "MailSize16StyleOutline" | "MailSize24StyleFill" | "MailSize24StyleOutline" | "MailSize28StyleFill" | "MailSize28StyleOutline" | "MailSize44StyleFill" | "MailSize44StyleOutline"
  | "MapSize16StyleFill" | "MapSize16StyleOutline" | "MapSize24StyleFill" | "MapSize24StyleOutline" | "MapSize32StyleFill" | "MapSize32StyleOutline" | "MapSize44StyleFill" | "MapSize44StyleOutline"
  | "MenuSize16StyleOutline" | "MenuSize24StyleOutline" | "MenuSize32StyleOutline"
  | "MessageBubbleSize16StyleFill" | "MessageBubbleSize16StyleOutline" | "MessageBubbleSize24StyleFill" | "MessageBubbleSize24StyleOutline" | "MessageBubbleSize28StyleFill" | "MessageBubbleSize28StyleOutline"
  | "MinusSize16StyleOutline" | "MinusSize24StyleOutline" | "MinusSize32StyleOutline"
  | "MinusCircleSize16StyleFill" | "MinusCircleSize16StyleOutline" | "MinusCircleSize24StyleFill" | "MinusCircleSize24StyleOutline" | "MinusCircleSize32StyleFill" | "MinusCircleSize32StyleOutline"
  | "MobileSize16StyleFill" | "MobileSize16StyleOutline" | "MobileSize24StyleFill" | "MobileSize24StyleOutline" | "MobileSize32StyleFill" | "MobileSize32StyleOutline" | "MobileSize44StyleFill" | "MobileSize44StyleOutline"
  | "MonitorSize16StyleFill" | "MonitorSize16StyleOutline" | "MonitorSize24StyleFill" | "MonitorSize24StyleOutline" | "MonitorSize44StyleFill" | "MonitorSize44StyleOutline"
  | "MoreSize16StyleOutline" | "MoreSize24StyleOutline" | "MoreSize32StyleOutline"
  | "NewsSize16StyleFill" | "NewsSize16StyleOutline" | "NewsSize24StyleFill" | "NewsSize24StyleOutline"
  | "OpenBookSize16StyleFill" | "OpenBookSize16StyleOutline" | "OpenBookSize24StyleFill" | "OpenBookSize24StyleOutline" | "OpenBookSize32StyleFill" | "OpenBookSize32StyleOutline"
  | "OpenInNewSize16StyleOutline" | "OpenInNewSize24StyleOutline"
  | "ParametersSize16StyleFill" | "ParametersSize16StyleOutline" | "ParametersSize24StyleFill" | "ParametersSize24StyleOutline" | "ParametersSize32StyleFill" | "ParametersSize32StyleOutline" | "ParametersSize44StyleFill" | "ParametersSize44StyleOutline"
  | "PictureSize16StyleFill" | "PictureSize16StyleOutline" | "PictureSize24StyleFill" | "PictureSize24StyleOutline" | "PictureSize44StyleFill" | "PictureSize44StyleOutline"
  | "PlusSize16StyleOutline" | "PlusSize24StyleOutline" | "PlusSize32StyleOutline" | "PlusSize44StyleOutline"
  | "PlusCircleSize16StyleFill" | "PlusCircleSize16StyleOutline" | "PlusCircleSize24StyleFill" | "PlusCircleSize24StyleOutline" | "PlusCircleSize28StyleFill" | "PlusCircleSize28StyleOutline" | "PlusCircleSize44StyleFill" | "PlusCircleSize44StyleOutline"
  | "PrintSize16StyleFill" | "PrintSize16StyleOutline" | "PrintSize24StyleFill" | "PrintSize24StyleOutline"
  | "ProfileSize16StyleFill" | "ProfileSize16StyleOutline" | "ProfileSize24StyleFill" | "ProfileSize24StyleOutline" | "ProfileSize28StyleFill" | "ProfileSize28StyleOutline" | "ProfileSize32StyleFill" | "ProfileSize32StyleOutline"
  | "QuestionCircleSize16StyleFill" | "QuestionCircleSize16StyleOutline" | "QuestionCircleSize24StyleFill" | "QuestionCircleSize24StyleOutline" | "QuestionCircleSize32StyleFill" | "QuestionCircleSize32StyleOutline"
  | "QuestionSize16StyleOutline" | "QuestionSize24StyleOutline" | "QuestionSize44StyleOutline"
  | "ReplySize16StyleOutline" | "ReplySize24StyleOutline"
  | "ReturnSize16StyleOutline" | "ReturnSize24StyleOutline" | "ReturnSize44StyleOutline"
  | "RubleCircleSize16StyleFill" | "RubleCircleSize16StyleOutline" | "RubleCircleSize24StyleFill" | "RubleCircleSize24StyleOutline" | "RubleCircleSize44StyleFill" | "RubleCircleSize44StyleOutline"
  | "RubleSize16StyleOutline" | "RubleSize24StyleOutline"
  | "SearchSize16StyleOutline" | "SearchSize24StyleOutline" | "SearchSize28StyleOutline" | "SearchSize32StyleOutline" | "SearchSize44StyleOutline"
  | "SendSize16StyleFill" | "SendSize16StyleOutline" | "SendSize24StyleFill" | "SendSize24StyleOutline" | "SendSize32StyleFill" | "SendSize32StyleOutline"
  | "SettingsSize16StyleFill" | "SettingsSize16StyleOutline" | "SettingsSize24StyleFill" | "SettingsSize24StyleOutline" | "SettingsSize28StyleFill" | "SettingsSize28StyleOutline" | "SettingsSize32StyleFill" | "SettingsSize32StyleOutline" | "SettingsSize44StyleFill" | "SettingsSize44StyleOutline"
  | "ShareSize16StyleFill" | "ShareSize16StyleOutline" | "ShareSize24StyleFill" | "ShareSize24StyleOutline" | "ShareSize32StyleFill" | "ShareSize32StyleOutline"
  | "ShieldSize16StyleFill" | "ShieldSize16StyleOutline" | "ShieldSize24StyleFill" | "ShieldSize24StyleOutline" | "ShieldSize44StyleFill" | "ShieldSize44StyleOutline"
  | "ShieldCheckSize16StyleFill" | "ShieldCheckSize16StyleOutline" | "ShieldCheckSize24StyleFill" | "ShieldCheckSize24StyleOutline" | "ShieldCheckSize44StyleFill" | "ShieldCheckSize44StyleOutline"
  | "ShowSize16StyleFill" | "ShowSize16StyleOutline" | "ShowSize24StyleFill" | "ShowSize24StyleOutline" | "ShowSize32StyleFill" | "ShowSize32StyleOutline" | "ShowSize44StyleFill" | "ShowSize44StyleOutline"
  | "SortingAscendingSize16StyleOutline" | "SortingAscendingSize24StyleOutline"
  | "SortingDescendingSize16StyleOutline" | "SortingDescendingSize24StyleOutline"
  | "StarSize16StyleFill" | "StarSize16StyleOutline" | "StarSize24StyleFill" | "StarSize24StyleOutline" | "StarSize28StyleFill" | "StarSize28StyleOutline" | "StarSize32StyleFill" | "StarSize32StyleOutline" | "StarSize44StyleFill" | "StarSize44StyleOutline"
  | "StatisticsSize16StyleFill" | "StatisticsSize16StyleOutline" | "StatisticsSize24StyleFill" | "StatisticsSize24StyleOutline" | "StatisticsSize44StyleFill" | "StatisticsSize44StyleOutline"
  | "SubscriptionSize16StyleFill" | "SubscriptionSize16StyleOutline" | "SubscriptionSize24StyleFill" | "SubscriptionSize24StyleOutline"
  | "SwapSize16StyleOutline" | "SwapSize24StyleOutline" | "SwapSize44StyleOutline"
  | "TriangleArrowDownSize16StyleFill" | "TriangleArrowDownSize24StyleFill" | "TriangleArrowDownSize44StyleFill"
  | "TriangleArrowLeftSize16StyleFill" | "TriangleArrowLeftSize24StyleFill" | "TriangleArrowLeftSize44StyleFill"
  | "TriangleArrowRightSize16StyleFill" | "TriangleArrowRightSize24StyleFill" | "TriangleArrowRightSize44StyleFill"
  | "TriangleArrowUpSize16StyleFill" | "TriangleArrowUpSize24StyleFill" | "TriangleArrowUpSize44StyleFill"
  | "TriangleArrowsUpAndDownSize16StyleFill" | "TriangleArrowsUpAndDownSize24StyleFill"
  | "UpdateSize16StyleOutline" | "UpdateSize24StyleOutline" | "UpdateSize32StyleOutline"
  | "UploadCircleSize16StyleFill" | "UploadCircleSize16StyleOutline" | "UploadCircleSize24StyleFill" | "UploadCircleSize24StyleOutline"
  | "UserSize16StyleFill" | "UserSize16StyleOutline" | "UserSize24StyleFill" | "UserSize24StyleOutline"
  | "ViewTableSize16StyleOutline" | "ViewTableSize24StyleOutline"
  | "WaitingSize16StyleFill" | "WaitingSize16StyleOutline" | "WaitingSize24StyleFill" | "WaitingSize24StyleOutline" | "WaitingSize44StyleFill" | "WaitingSize44StyleOutline"
  | "WalletSize16StyleFill" | "WalletSize16StyleOutline" | "WalletSize24StyleFill" | "WalletSize24StyleOutline" | "WalletSize28StyleFill" | "WalletSize28StyleOutline" | "WalletSize44StyleFill" | "WalletSize44StyleOutline"
  | "WarningCircleSize16StyleFill" | "WarningCircleSize16StyleOutline" | "WarningCircleSize24StyleFill" | "WarningCircleSize24StyleOutline" | "WarningCircleSize32StyleFill" | "WarningCircleSize32StyleOutline" | "WarningCircleSize44StyleFill" | "WarningCircleSize44StyleOutline"
  | "WarningSize16StyleOutline" | "WarningSize24StyleOutline" | "WarningSize44StyleOutline"
  | "ZoomInSize24StyleOutline" | "ZoomOutSize24StyleFill";

export interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: IconName;
  size?: number | string;
}
export declare const Icon: React.FC<IconProps>;
export default Icon;
